name: Invoke API

on:
  schedule:
    - cron: '*/23 */2 * * *'
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#providing-inputs
  workflow_dispatch:
    inputs:
      unconditional-invoking:
        description: 'Invoke API'
        type: boolean
        required: true
        default: true

jobs:
  Invoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make a decision
        id: decision
        run: [ $((($(date "+%-m") + $(date "+%-d") + $(date "+%-H")) % 2)) = 0 ] && (echo "runnable=true" >> $GITHUB_OUTPUT)

      - name: Set up python
        if: steps.decision.outputs.runnable == 'true'
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 'Install dependencies'
        if: steps.decision.outputs.runnable == 'true'
        run: python -m pip install --upgrade requests

      - name: Run Api
        if: steps.decision.outputs.runnable == 'true'
        env:
          id: ${{ secrets.ID }}
          secret: ${{ secrets.SECRET }}
          token: ${{ secrets.TOKEN }}
        run: python e5.py
